In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings as war

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [4]:
dataset=dataset.drop("User ID",axis=1)

In [6]:
print(dataset["Purchased"].value_counts())

Purchased
0    257
1    143
Name: count, dtype: int64


In [7]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [8]:
indep.shape

(400, 3)

In [9]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = .30, random_state = 0)

In [ ]:
'''The MultinomialNB class in scikit-learn implements the Naive Bayes algorithm for multinomially distributed data,
which is suitable for classification tasks with discrete features.
It is commonly used in text classification problems where the features represent the frequency of words or other discrete data.'''

In [11]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report,accuracy_score
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy score is: ",accuracy)

              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

[[68 11]
 [28 13]]
Accuracy score is:  0.675


In [ ]:
'''The BernoulliNB class in scikit-learn is an implementation of the Naive Bayes classifier for Bernoulli distributed data.
It assumes that all features are binary (i.e., boolean or Bernoulli distributed). 
This classifier is suitable for classification tasks where the features are binary-valued, such as word presence/absence in text classification'''

In [22]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report,accuracy_score,f1_score
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy score is               : ",accuracy)
f1=f1_score(y_test,y_pred)
print("f1 score for purchased class is : ",f1)
war.filterwarnings("ignore")

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

[[79  0]
 [41  0]]
Accuracy score is               :  0.6583333333333333
f1 score for purchased class is :  0.0


In [17]:
'''The CategoricalNB classifier would be suitable for categorical data, where features are categorical rather than binary. 
Categorical data consists of discrete variables that represent categories or groups.'''

'The CategoricalNB classifier would be suitable for categorical data, where features are categorical rather than binary. \nCategorical data consists of discrete variables that represent categories or groups.'

In [23]:
from sklearn.naive_bayes import CategoricalNB
Catclassifier =CategoricalNB()
Catclassifier.fit(X_train, y_train)
y_pred = Catclassifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report,accuracy_score
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy score is               : ",accuracy)
f1=f1_score(y_test,y_pred)
print("f1 score for purchased class is : ",f1)

              precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120

[[76  3]
 [ 9 32]]
Accuracy score is               :  0.9
f1 score for purchased class is :  0.8421052631578947


In [ ]:

'''ComplementNB is a variation of the Naive Bayes algorithm, specifically designed to handle imbalanced datasets. 
It is well-suited for text classification tasks, especially when the classes are highly imbalanced.'''

In [19]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report,accuracy_score
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)
print("Accuracy score is               : ",accuracy)
f1=f1_score(y_test,y_pred)
print("f1 score for purchased class is : ",f1)


              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120

[[42 37]
 [20 21]]
Accuracy score is               :  0.9
f1 score for purchased class is :  0.42424242424242425


In [26]:
#To predict Either purchased class or Not purchased class
prediction=Catclassifier.predict([[50,20000,False]])
print(prediction)
prediction=Catclassifier.predict([[19,19000,True]])
print(prediction)
war.filterwarnings("ignore")

[1]
[0]


In [ ]:
#Best model is CategoricalNB

In [27]:
import pickle
filename='finalized_model_MLClassification_CategoricalNB.sav'
pickle.dump(Catclassifier,open(filename,'wb'))

In [33]:
loaded_model=pickle.load(open('finalized_model_MLClassification_CategoricalNB.sav','rb'))
result=loaded_model.predict([[50,20000,False]])
result1=loaded_model.predict([[19,19000,True]])
print(result)
print(result1)

[1]
[0]
